HAccelerator/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^HealthNet/', include('HealthNet.urls')),
    url(r'^admin/', admin.site.urls),
]

admin.site.site_header = 'HealthNet R2'

HealthNet/urls.py
# File: urls.py
# Description: This file contains the Django url statements.
# Author(s): Team Suites (1)

# imports
from django.conf.urls import url
from . import views

# url statements
app_name = 'HealthNet'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.registerP, name='registerP'),
    url(r'^register/create$', views.createPLogIn, name='createPLogIn'),
    url(r'^password/$', views.password, name='password'),
    url(r'^password/changepass/$', views.changePass, name='changepass'),
    url(r'^verify/$', views.verify, name='verify'),
    url(r'^home/$', views.home, name='home'),
    url(r'^home/registerDN$', views.registerDN, name='registerDN'),
    url(r'^home/registerDN/createDN$', views.createDNLogIn, name='createDNLogIn'),
    url(r'^information/$', views.information, name='information'),
    url(r'^information/updatePro$', views.updatePro, name='updatePro'),
    url(r'^information/updatePro/updateProInfo$', views.updateProInfo, name='updateProInfo'),
    url(r'^information/updateMed/(?P<pat_id>[0-9]+)/', views.updateMed, name='updateMed'),
    url(r'^information/updateMed/updateMedInfo/(?P<pat_id>[0-9]+)/', views.updateMedInfo, name='updateMedInfo'),
    url(r'^information/export$', views.export, name='export'),
    url(r'^information/tests/(?P<pat_id>[0-9]+)/', views.tests, name='tests'),
    url(r'^information/tests/createTest/(?P<pat_id>[0-9]+)/', views.createTest, name='createTest'),
    url(r'^information/tests/createTest/createTestInfo/(?P<pat_id>[0-9]+)/', views.createTestInfo, name='createTestInfo'),
    url(r'^information/tests/releaseTest/(?P<test_id>[0-9]+)/', views.releaseTest, name='releaseTest'),
    url(r'^information/testDetails/(?P<test_id>[0-9]+)/', views.testDetails, name='testDetails'),
    url(r'^information/discharge/(?P<pat_id>[0-9]+)/', views.discharge, name='discharge'),
    url(r'^information/admission/(?P<pat_id>[0-9]+)/(?P<emp_id>[0-9]+)/', views.admission, name='admission'),
    url(r'^information/transfer/(?P<pat_id>[0-9]+)/(?P<emp_id>[0-9]+)/', views.transfer, name='transfer'),
    url(r'^appointments/$', views.appointments, name='appointments'),
    url(r'^appointments/createAppt$', views.createAppt, name='createAppt'),
    url(r'^appointments/createAppt/createApptInfo$', views.createApptInfo, name="createApptInfo"),
    url(r'^appointments/updateAppt/(?P<appt_id>[0-9]+)/', views.updateAppt, name='updateAppt'),
    url(r'^appointments/updateAppt/updateApptInfo/(?P<appt_id>[0-9]+)/', views.updateApptInfo, name='updateApptInfo'),
    url(r'^appointments/cancelAppt/(?P<appt_id>[0-9]+)/', views.cancelAppt, name='cancelAppt'),
    url(r'^prescriptions/$', views.prescriptions, name='prescriptions'),
    url(r'^prescriptions/createPres$', views.createPres, name='createPres'),
    url(r'^prescriptions/createPres/createPresInfo$', views.createPresInfo, name="createPresInfo"),
    url(r'^prescriptions/updatePres/(?P<pres_id>[0-9]+)/', views.updatePres, name='updatePres'),
    url(r'^prescriptions/updatePres/updatePresInfo/(?P<pres_id>[0-9]+)/', views.updatePresInfo, name='updatePresInfo'),
    url(r'^prescriptions/removePres/(?P<pres_id>[0-9]+)/', views.removePres, name='removePres'),
    url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^messages/$', views.messages, name='messages'),
    url(r'^messages/createMess/$', views.createMess, name='createMess'),
    url(r'^messages/createMess/createMessInfo/(?P<mess_id>-1)/', views.createMessInfo, name="createMessInfo"),
    url(r'^messages/replyMess/(?P<mess_id>[0-9]+)/', views.replyMess, name='replyMess'),
    url(r'^messages/replyMess/createMessInfo/(?P<mess_id>[0-9]+)/', views.createMessInfo, name="createMessInfo"),
    url(r'^messages/viewMess/(?P<mess_id>[0-9]+)/', views.viewMess, name='viewMess'),
    url(r'^messages/deleteMess/(?P<mess_id>[0-9]+)/', views.deleteMess, name='deleteMess'),
    url(r'^log/$', views.log, name='log'),
    url(r'^statistics/$', views.statistics, name='statistics'),
    url(r'^logOut/$', views.logOut, name='logOut')
]

HealthNet/views.py
# File: views.py
# Description: This file contains Python and Django code which will form the
#              Controller element of the Model-Template-Controller (MTC) design
#              pattern.
# Author(s): Team Suites (1)

# imports
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Test
from .models import Patient
from .models import EmergencyContact
from .models import Doctor
from .models import Nurse
from .models import Prescription
from .models import Hospital
from .models import Appointment
from .models import LogInInfo
from .models import Administrator
from .models import Message
from django.core.exceptions import ObjectDoesNotExist
from django.utils.datastructures import MultiValueDictKeyError
import datetime
from datetime import date
import os
import csv

# This variable is for storing the username entered when a user logs-in
uname = ''


# This module handles the logging of activities by saving logs to a plaintext file which is then rendered
# in HTML for administrators to view.
def logActivity(activity):
    filename = "log.txt"
    cwd = os.getcwd()
    target = open(cwd + "\\HealthNet\\log\\" + filename, 'a')
    target.write(activity)
    target.write("\n")
    target.close()


# This module handles the generic template view for the index page in which users will log-in or register
# if they have not made credentials.
class IndexView(generic.ListView):
    template_name = 'HealthNet/index.html'
    context_object_name = 'user_login_information'

    def get_queryset(self):
        return LogInInfo.objects.order_by('-username')


# This module simply renders the HTML page for the registration screen.
def registerP(request):
    return render(request, 'HealthNet/registerP.html')


# This module handles the user registration. The "LogInInfo" object is used to store their credentials in the database.
def createPLogIn(request):
    firstName = (request.POST['firstName'])
    lastName = (request.POST['lastName'])
    address = (request.POST['address'])
    number = (request.POST['number'])
    email = (request.POST['email'])
    provider = (request.POST['provider'])
    insuranceid = (request.POST['insuranceid'])
    contactfname = (request.POST['contactfname'])
    contactlname = (request.POST['contactlname'])
    contactaddress = (request.POST['contactaddress'])
    contactnumber = (request.POST['contactnumber'])
    height = (request.POST['height'])
    weight = (request.POST['weight'])
    allergies = (request.POST['allergies'])
    gender = (request.POST['gender'])
    username = (request.POST['username'])
    password = (request.POST['password'])
    try:
        logininfo = LogInInfo.objects.get(username=username)
    except ObjectDoesNotExist:
        LogInInfo.objects.create(username=username, password=password)
        global uname
        uname = username
        try:
            contact = EmergencyContact.objects.get(firstName=contactfname, lastName=contactlname,
                                                      address=contactaddress, number=contactnumber)
        except ObjectDoesNotExist:
            contact = EmergencyContact.objects.create(firstName=contactfname, lastName=contactlname,
                                                      address=contactaddress, number=contactnumber)
        Patient.objects.create(username=uname)
        patient = Patient.objects.get(username=uname)
        patient.firstName = firstName
        patient.lastName = lastName
        patient.address = address
        patient.number = number
        patient.email = email
        patient.provider = provider
        patient.insuranceid = insuranceid
        patient.contact = contact
        patient.height = height
        patient.weight = weight
        patient.allergies = allergies
        patient.gender = gender
        patient.save()

        activity = "User " + username + " registered a new account - logged on: " +\
                   datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
        logActivity(activity)
        return HttpResponseRedirect(reverse('HealthNet:home', args=()))
    else:
        return render(request, 'HealthNet/registerP.html', {
            'username': username,
            'error_message': "Username already exists.",
        })


# This module simply renders the HTML page for the password change screen.
def password(request):
    return render(request, 'HealthNet/password.html')


# This module handles the changing of a user's password
def changePass(request):
    try:
        username = (request.POST["username"])
        newpass = (request.POST["password"])
        currinfo = LogInInfo.objects.get(username=username)
    except LogInInfo.DoesNotExist:
        return render(request, 'HealthNet/password.html', {
            'username': username,
            'error_message': "There was a problem with your username.",
            })
    else:
        currinfo.password = newpass
        currinfo.save()
        activity = "User " + username + " changed their password - logged on: " +\
                   datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
        logActivity(activity)
        return HttpResponseRedirect(reverse('HealthNet:index', args=()))


# This module handles the attempt of a user to log-in to their profile. If the username and password are valid,
# the user is redirected to their profile. If not, an error message is generated and the user is
# redirected to the index page.
def verify(request):
    username = (request.POST['username'])
    passwordInput = (request.POST['password'])
    try:
        current = LogInInfo.objects.get(username=username)
    except LogInInfo.DoesNotExist:
        return render(request, 'HealthNet/index.html', {
            'username': username,
            'error_message': "There was a problem with your username.",
        })
    else:
        passwordActual = current.password
        if passwordInput == passwordActual:
            global uname
            uname = username
            activity = "User " + username + " logged in - logged on: " + datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
            logActivity(activity)
            return HttpResponseRedirect(reverse('HealthNet:home', args=()))
        else:
            return render(request, 'HealthNet/index.html', {
                'username': username,
                'error_message': "There was a problem with your password.",
            })


# This module simply renders the home page for a user
def home(request):
    try:
        p = Patient.objects.get(username=uname)
    except Patient.DoesNotExist:
        try:
            d = Doctor.objects.get(username=uname)
        except Doctor.DoesNotExist:
            try:
                n = Nurse.objects.get(username=uname)
            except Nurse.DoesNotExist:
                try:
                    a = Administrator.objects.get(username=uname)
                except Administrator.DoesNotExist:
                    return render(request, 'HealthNet/index.html', {
                        'error_message': "An error has occurred"
                        })
                else:
                    utype = "Administrator"
                    context = {'user': a,
                               'type': utype}
                    return render(request, 'HealthNet/home.html', context)
            else:
                utype = "Nurse"
                context = {'user': n,
                           'type': utype}
                return render(request, 'HealthNet/home.html', context)
        else:
            utype = "Doctor"
            context = {'user': d,
                       'type': utype}
            return render(request, 'HealthNet/home.html', context)
    else:
        utype = "Patient"
        context = {'user': p,
                   'type': utype}
        return render(request, 'HealthNet/home.html', context)


# This module simply renders the HTML page for the doctor and nurse registration screen.
def registerDN(request):
    workplaces = Hospital.objects.order_by("-name")
    admin = Administrator.objects.get(username=uname)
    context = {'workplaces': workplaces,
               'admin': admin}
    return render(request, 'HealthNet/registerDN.html', context)


# This module handles the doctor and nurse registration. The "LogInInfo" object is used to store their credentials
# in the database.
def createDNLogIn(request):
    firstName = (request.POST['firstName'])
    lastName = (request.POST['lastName'])
    type = (request.POST['type'])
    username = (request.POST['username'])
    password = (request.POST['password'])
    admin = Administrator.objects.get(username=uname)
    try:
        logininfo = LogInInfo.objects.get(username=username)
    except ObjectDoesNotExist:
        LogInInfo.objects.create(username=username, password=password)
        if type == "Doctor":
            Doctor.objects.create(username=username, firstName=firstName, lastName=lastName)
            d = Doctor.objects.get(username=username)
            d.workplace = admin.workplace
            d.save()
            activity = "Administrator " + uname + " registered a new doctor account - logged on: " + \
                       datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
            logActivity(activity)
            return HttpResponseRedirect(reverse('HealthNet:home', args=()))
        elif type == "Nurse":
            Nurse.objects.create(username=username,  firstName=firstName, lastName=lastName)
            n = Nurse.objects.get(username=username)
            n.workplace = admin.workplace
            n.save()
            activity = "Administrator " + uname + " registered a new nurse account - logged on: " + \
                       datetime.datetime.now().strftime('%m/%d/%y @ %H:%M:%S')
            logActivity(activity)

HealthNet/templates/HealthNet/appointments.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/mainPages.css' %}" />
<link rel='shortcut icon' href={% static 'HAccelerator/images/favicon.ico' %} type='images/favicon' />

<head>
	<title>HealthNet | Appointments</title>
</head>

<ul class="nav">
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:home' %}">Home</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:information' %}">User Information</a></li>
	<li class="nav_container"><a class="nav_item_active" href="{% url 'HealthNet:appointments' %}">Manage Appointments</a></li>
    <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:prescriptions' %}">Prescriptions</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:calendar' %}">Calendar</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:messages' %}">Messages</a></li>
	<li style="float:right" class="nav_container"><a class="nav_items" href="{% url 'HealthNet:logOut' %}">Log Out</a></li>
</ul>

<body>
    <div id="container">
        <div id="tablecontainer">

            {% if error_message %}
                <div id="alert" >
                    <strong>{{ error_message }}</strong>
                </div>
            {% endif %}

            {% if type == "Patient" %}
                <h2><span style="text-decoration: underline;">{{ user.firstName }} {{ user.lastName }}</span>, These Are Your Appointments</h2>
                {% if appointments %}
                    <table>
                        <tr>
                            <th>Date And Time</th>
                            <th>Doctor</th>
                            <th>Location</th>
                            <th></th>
                        </tr>
                        {% for appointment in appointments %}
                            <tr>
                                <td><a class="alink" href="{% url 'HealthNet:updateAppt' appointment.id %}">
                                    {{ appointment.month }}.{{ appointment.day }}.{{ appointment.year }},
                                    {{ appointment.appttime }} {{ appointment.phase }}
                                </a></td>
                                <td>{{ appointment.doctor }}</td>
                                <td>{{ appointment.location }}</td>
                                <td><form action="{% url 'HealthNet:cancelAppt' appointment.id %}"><input type="submit" value="Cancel" /></form></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>You have no scheduled appointments.</p>
                {% endif %}

                <br>

                <form action="{% url 'HealthNet:createAppt' %}">
                    <input type="submit" value="Create Appointment" />
                </form>
            {% endif %}

            {% if type == "Doctor" %}
                <h2>Appointments at <span style="text-decoration: underline;">{{ employee.workplace.name }}</span></h2>
                {% if appointments %}
                    <table>
                        <tr>
                            <th>Date And Time</th>
                            <th>Patient</th>
                            <th>Doctor</th>
                        </tr>
                        {% for appointment in appointments %}
                            <tr>
                                <td><a class="alink" href="{% url 'HealthNet:updateAppt' appointment.id %}">
                                    {{ appointment.month }}.{{ appointment.day }}.{{ appointment.year }},
                                    {{ appointment.appttime }} {{ appointment.phase }}
                                </a></td>
                                <td>{{ appointment.patient }}</td>
                                <td>{{ appointment.doctor }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>At the moment, there are no appointments at your workplace.</p>
                {% endif %}
                <hr />
                <h2>Appointments scheduled with you, <span style="text-decoration: underline;">{{ employee.firstName }} {{ employee.lastName }}</span></h2>
                {% if this_appointments %}
                    <table>
                        <tr>
                            <th>Date And Time</th>
                            <th>Patient</th>
                            <th>Location</th>
                            <th></th>
                        </tr>
                        {% for appointment in this_appointments %}
                            <tr>
                                <td><a class="alink" href="{% url 'HealthNet:updateAppt' appointment.id %}">
                                    {{ appointment.month }}.{{ appointment.day }}.{{ appointment.year }},
                                    {{ appointment.appttime }} {{ appointment.phase }}
                                </a></td>
                                <td>{{ appointment.patient }}</td>
                                <td>{{ appointment.location }}</td>
                                <td><form action="{% url 'HealthNet:cancelAppt' appointment.id %}"><input type="submit" value="Cancel" /></form></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>You have no scheduled appointments.</p>
                {% endif %}

                <br>

                <form action="{% url 'HealthNet:createAppt' %}">
                    <input type="submit" value="Create Appointment" />
                </form>
            {% endif %}

            {% if type == "Nurse" %}
                <h2><span style="text-decoration: underline;">{{ employee.firstName }} {{ employee.lastName }}</span>,
                    these are the appointments at <span style="text-decoration: underline;">{{ employee.workplace.name }}</span></h2>
                {% if appointments %}
                    <table>
                        <tr>
                            <th>Date And Time</th>
                            <th>Patient</th>
                            <th>Doctor</th>
                        </tr>
                        {% for appointment in appointments %}
                            <tr>
                                <td><a class="alink" href="{% url 'HealthNet:updateAppt' appointment.id %}">
                                    {{ appointment.month }}.{{ appointment.day }}.{{ appointment.year }},
                                    {{ appointment.appttime }} {{ appointment.phase }}
                                </a></td>
                                <td>{{ appointment.patient }}</td>
                                <td>{{ appointment.doctor }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>At the moment, there are no appointments at your workplace.</p>
                {% endif %}

                <br>

                <form action="{% url 'HealthNet:createAppt' %}">
                    <input type="submit" value="Create Appointment" />
                </form>
            {% endif %}
        </div>
    </div>
</body>
</html>

HealthNet/templates/HealthNet/index.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/formPages.css' %}" />
<link rel='shortcut icon' href={% static 'HAccelerator/images/favicon.ico' %} type='images/favicon' />

<head>
	<title>HealthNet | Login</title>
	<script type="text/javascript">
		function checkform()
		{
			if (document.login.username.value.length==0)
			{
				alert("Please fill in your username");
				return false;
			}
			else if(document.login.password.value.length==0)
            {
                alert("Please enter your password");
                return false;
            }
			else
			{
				return true;
			}
		}
	</script>
</head>

<body>
    <div id="container">
        <div id="formContainer">
            <h1>Welcome to HealthNet!</h1>
            <h3>Enter your information below</h3>

            {% if error_message %}
                <div id="alert" >
                    <strong>{{ error_message }}</strong>
                </div>
            {% endif %}

            <form name = 'login' action="{% url 'HealthNet:verify' %}" method="post" onsubmit="return checkform();">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username"/>
                <input type="password" name="password" placeholder="Password"/>
                <input class="button" type="submit" value="Log In" />
            </form>

            <form action="{% url 'HealthNet:registerP' %}">
                <input class="button" type="submit" value="Register" />
            </form>

            <form action="{% url 'HealthNet:password' %}">
                <input class="button" type="submit" value="Forgot Your Password?" />
            </form>
        </div>
    </div>
</body>
</html>

HealthNet/templates/HealthNet/prescriptions.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/mainPages.css' %}" />
<link rel='shortcut icon' href={% static 'HAccelerator/images/favicon.ico' %} type='images/favicon' />

<head>
	<title>HealthNet | Prescriptions</title>
</head>

<ul class="nav">
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:home' %}">Home</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:information' %}">User Information</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:appointments' %}">Manage Appointments</a></li>
    <li class="nav_container"><a class="nav_item_active" href="{% url 'HealthNet:prescriptions' %}">Prescriptions</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:calendar' %}">Calendar</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:messages' %}">Messages</a></li>
	<li style="float:right" class="nav_container"><a class="nav_items" href="{% url 'HealthNet:logOut' %}">Log Out</a></li>
</ul>

<body>
    <div id="container">
        <div id="tablecontainer">
            {% if type == "Patient" %}
                <h2><span style="text-decoration: underline;">{{ patient.firstName }} {{ patient.lastName }}</span>, these are the prescriptions that have been assigned to you</h2>
            {% elif type == "Doctor" %}
                <h2><span style="text-decoration: underline;">{{ employee.firstName }} {{ employee.lastName }}</span>, these are the prescriptions that you have created</h2>
            {% else %}
                <h2><span style="text-decoration: underline;">{{ employee.firstName }} {{ employee.lastName }}</span>, these are the prescriptions for patients at <span style="text-decoration: underline;">{{ employee.workplace.name }}</span></h2>
            {% endif %}
            {% if prescriptions %}
	            <table>
                    <tr>
                        <th>Name</th>
                        <th>Dosage</th>
                        {% if type == "Patient"%}

                        {% else %}
                            <th>Patient</th>
                        {% endif %}

                        {% if type == "Doctor"%}
                            <th></th>
                        {% else %}
                            <th>Doctor</th>
                        {% endif %}
                    </tr>
                    {% for p in prescriptions %}
                        <tr>
                            {% if type == "Doctor"%}
                                <td><a href="{% url 'HealthNet:updatePres' p.id %}">{{ p.name }}</a></td>
                            {% else %}
                                <td>{{ p.name }}</td>
                            {% endif %}

                            <td>{{ p.dosage }}</td>

                            {% if type == "Patient"%}

                            {% else %}
                                <td>{{ p.patient }}</td>
                            {% endif %}

                            {% if type == "Doctor"%}
                                <td><form action="{% url 'HealthNet:removePres' p.id %}"><input type="submit" value="Remove" /></form></td>
                            {% else %}
                                <td>{{ p.doctor }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>There are no prescriptions to view</p>
            {% endif %}

            {% if type == "Doctor" %}
                <h2>These are the prescriptions for patients at <span style="text-decoration: underline;">{{ employee.workplace.name }}</span></h2>
                {% if presatw %}
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Dosage</th>
                            <th>Patient</th>
                            <th></th>
                        </tr>
                        {% for p in presatw %}
                            <tr>
                                <td><a href="{% url 'HealthNet:updatePres' p.id %}">{{ p.name }}</a></td>
                                <td>{{ p.dosage }}</td>
                                <td>{{ p.patient }}</td>
                                <td><form action="{% url 'HealthNet:removePres' p.id %}"><input type="submit" value="Remove" /></form></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>There are no prescriptions to view</p>
                {% endif %}

                <br>

                <form action="{% url 'HealthNet:createPres' %}">
                    <input type="submit" value="Create Prescription" />
                </form>
            {% endif %}
        </div>
    </div>
</body>
</html>

HealthNet/templates/HealthNet/tests.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'HAccelerator/mainPages.css' %}" />
<link rel='shortcut icon' href={% static 'HAccelerator/images/favicon.ico' %} type='images/favicon' />

<head>
	<title>HealthNet | Tests</title>
</head>

<ul class="nav">
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:home' %}">Home</a></li>
	<li class="nav_container"><a class="nav_item_active" href="{% url 'HealthNet:information' %}">User Information</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:appointments' %}">Manage Appointments</a></li>
    <li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:prescriptions' %}">Prescriptions</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:calendar' %}">Calendar</a></li>
	<li class="nav_container"><a class="nav_items" href="{% url 'HealthNet:messages' %}">Messages</a></li>
	<li style="float:right" class="nav_container"><a class="nav_items" href="{% url 'HealthNet:logOut' %}">Log Out</a></li>
</ul>

<body>
    <div id="container">
        <div id="tablecontainer">
            <h2>Tests</h2>
                {% if test %}
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Released?</th>
                            <th>Release</th>
                        </tr>
                        {% for t in test %}
                            <tr>
                                <td>{{ t.name }}</td>
                                {% if t.released == True %}
                                    <td>Released</td>
                                {% else %}
                                    <td>Unreleased</td>
                                {% endif %}
                                {% if t.released == True %}
                                    <td>Already Released</td>
                                {% else %}
                                    <td><form action="{% url 'HealthNet:releaseTest' t.id %}"><input type="submit" value="Release" /></form></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>There are no tests for this patient yet</p>
                {% endif %}

            <br>

            <form action="{% url 'HealthNet:createTest' patient.id%}">
                {% csrf_token %}
				<input type="submit" value="Create New Test" />
            </form>

            <br>

            <form action="{% url 'HealthNet:information' %}">
                <input class="button" type="submit" value="Return" />
            </form>
        </div>
    </div>
</body>
</html>